version: "3"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3001:3001
    restart: always

  mongo:
    image: "mongo"
    command: [--auth]
    ports: 
      - 27017:27017
    env_file:
      - .env
    volumes:
      - "../db:/data/db"
