version: "3"
services:
  web:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
  mongo:
    image: "mongo"
    command: [--auth]
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "../db:/data/db"
