version: "3"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3001:3001
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  mongo:
    image: "mongo"
    command: [--auth]
    env_file:
      - .env
    volumes:
      - "../db:/data/db"
